### ISSUE TITLE
Wording issue

### ISSUE THREAD

**Issue by cfx-gspos** [Conflux-Chain/conflux-doc#18]
![image](https://user-images.githubusercontent.com/5502154/81187591-d6f74200-8fe6-11ea-879f-580281f165fa.png)
![image](https://user-images.githubusercontent.com/5502154/81187631-e24a6d80-8fe6-11ea-94be-c9ed26e03cb1.png)

**Comment by cfx-gspos** [comment]
![image](https://user-images.githubusercontent.com/5502154/81195694-c64bc980-8ff0-11ea-8cc1-1b2533af1670.png)

**Comment by sparkmiw** [comment]
Fixed
