### ISSUE TITLE
The gas price of CREATE vs CREATE2

### ISSUE THREAD

**Issue by Regulusyg** [Conflux-Chain/conflux-doc#22]
In the current implementation, the gas price of CREATE and CREATE2 follows the same definition as in Ethereum:
CREATE costs G_create, 
CREATE2 costs G_create+G_sha3word × ⌈μ [2] ÷ 32⌉,  
where the additional cost of CREATE2 corresponds to hashing on the initialization code of length μ [2] bytes.

Actually, the difference in gas price in Ethereum is introduced because the resultant contract address by CREATE is simply the rightmost 160-bits of Kec(RLP(s,n)) without the hash value of initialization code where as the address by CREATE2 includes such a hash value.

In Conflux we include the hash value of initialization code in both cases of CREATE and CREATE2, so that the discrimination in gas price does not make much sense.
Therefore I think it would be better if we change the price of CREATE to the same as CREATE2.

**Comment by sparkmiw** [comment]
Good catch. I agree.

**Comment by Regulusyg** [comment]
Just realized that I opened this issue in conflux-doc instead of conflux-rust...
